= Legacy Code Starter

A small starter to get you started testing legacy code.
This repo just shows some techniques that you can use before you start one of the legacy code katas.

Shows how to test a legacy method with `void` return by using classical link:src/test/java/de/richargh/legacy/starter/LegacyTest.java[regular Junit5] and with by using classical link:src/test/java/de/richargh/legacy/starter/LegacyApprovalTest.java[approval test library].

If you are working in a legacy code scenario you should definitely check out link:https://www.youtube.com/watch?v=zyM2Ep28ED8[Introducing the Gilded Rose kata and writing test cases using Approval Tests by Emily Bache].

One thing of note: the code has a random number generator. With minimal code changes you can make that side effect deterministic by writing `random.setSeed()` or `new Random(seed)`.

== Preconditions

* Install the right java version.
** If you have link:https://sdkman.io/[SDK Man] installed, call `sdk use env` to install the version from link:.sdkmanrc[.sdkmanrc]
* Have Maven installed

== Leagcy Code Kata

* link:https://github.com/jbrains/trivia[Trivia]
* link:https://github.com/emilybache/GildedRose-Refactoring-Kata[Gilded Rose]


